<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\RealEstateEntity;
class RealEstateEntityDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $realEstateData = array(
            array('name' => 'Time Square', 'real_state_type' => 'house', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '123456789', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here', 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'department', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '123456789', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'land', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '123456789', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'commercial_ground', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '987874546-87', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'house', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '123456789', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here', 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'department', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '123456789', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here', 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'land', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '123456789', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'commercial_ground', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '987874546-87', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'house', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '123456789', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here', 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'department', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '123456789', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here', 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'land', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '123456789', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'commercial_ground', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '987874546-87', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'house', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '123456789', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here', 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'department', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '123456789', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here', 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'land', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '123456789', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'commercial_ground', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '987874546-87', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'house', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '123456789', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here', 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'department', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '123456789', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here', 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'land', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '123456789', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'commercial_ground', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '987874546-87', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'house', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '123456789', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here', 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'department', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '123456789', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here', 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'land', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '123456789', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here'),
            array('name' => 'Time Square', 'real_state_type' => 'commercial_ground', 'street' => 'Maple County Rd, Bodakdev', 'external_number' => 'TEST-123456', 'internal_number' => '987874546-87', 'neighborhood' => 'Test neighboor', 'city' => 'Ahmedabad', 'country' => 'IN', 'rooms' => 3, 'bathrooms' => 2, 'comments' => 'Test comment goes here')
        );
        RealEstateEntity::insert($realEstateData);
    }
}
